// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iryzhsrcnbcptqsncoxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlyeXpoc3JjbmJjcHRxc25jb3hjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2ODcyMDcsImV4cCI6MjA2NjI2MzIwN30.TFlyeeEeI9gxVhUFlGdCsuPm1M2Onqw_LA1Z2H3GNYk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});