// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mmsusbxwqnplttvvvjsi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1tc3VzYnh3cW5wbHR0dnZ2anNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NDgxMTUsImV4cCI6MjA2NzAyNDExNX0.GhwgM2WeK4cn-cwt2liXpYQfQvIo53T6pQ1rw6lDIEQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});